openapi: 3.0.0
info:
  title: Developer Social Network API
  version: 1.0.0
  description: Documentación de la API usando Swagger
servers:
  - url: http://ec2-100-25-217-101.compute-1.amazonaws.com
  - url: http://localhost:4000/api/v1
    description: Sandbox server (uses test data)
tags:
  - name: Posts
    description: API para gestionar posts
paths:
  /post:
    $ref: "./paths/post.yaml"
  /post/{id}:
    $ref: "./paths/post-by-id.yaml"
  /api/v1/project:
    $ref: "./paths/project.yaml"
  /api/v1/project/{id}:
    $ref: "./paths/project-by-id.yaml"
