openapi: 3.0.0
info:
  title: Developer Social Network API
  version: 1.0.0
  description: Documentación de la API usando Swagger
servers:
  - url: https://mrmolanodev.site/api/v1
    description: Production server
  - url: http://localhost:3000/api/v1
    description: Sandbox server (uses test data)
tags:
  - name: Posts
    description: API para gestionar posts
  - name: Project
    description: API para gestionar projects
  - name: Authentication
    description: API para autenticar usuarios
  - name: Users
    description: API para gestionar usuarios
  - name: Technologies
    description: API para gestionar tecnologias
  - name: Comment
    description: API para gestionar comentarios
  - name: Social Networks
    description: API para gestionar las redes sociales de un usuario
  - name: Notification
    description: API para gestionar notificaciones
paths:
  # Post endpoints
  /post:
    $ref: './paths/post.yaml'
  /post/{id}:
    $ref: './paths/post-by-id.yaml'
  /post/{id}/followed:
    $ref: './paths/post-followed-by-id.yaml'
  /post/user/{userid}:
    $ref: './paths/post-user.yaml'
  /post/{id}/like:
    $ref: './paths/post/post-like.yaml'
  # Project endpoints
  /project:
    $ref: './paths/project.yaml'
  /project/user/{userid}:
    $ref: './paths/user/user-project.yaml'
  /project/user/{userid}/liked:
    $ref: './paths/user/user-project-liked.yaml'
  /project/{id}:
    $ref: './paths/project-by-id.yaml'

  # Technology endpoints
  /technology:
    $ref: './paths/technology.yaml'
  /technology/{name}:
    $ref: './paths/technology-by-name.yaml'

  # User endpoints
  /user:
    $ref: './paths/user.yaml'
  /user/role/{role}:
    $ref: './paths/user/user-role.yaml'
  /user/{id}:
    $ref: './paths/user-by-id.yaml'
  /user/{id}/followers:
    $ref: './paths/user/user-followers.yaml'
  /user/{id}/followed:
    $ref: './paths/user/user-followed.yaml'

  # Comment endpoints
  /comment:
    $ref: './paths/comment.yaml'
  /comment/{id}:
    $ref: './paths/comment-by-id.yaml'

  # Auth endpoints
  /auth/register:
    $ref: './paths/register.yaml'
  /auth/login:
    $ref: './paths/login.yaml'
  /auth/me:
    $ref: './paths/login.yaml'

  # Like endpoints
  /like/user/{userid}:
    $ref: './paths/user-like.yaml'

  # Social networks endpoints
  /social-networks:
    $ref: './paths/social-networks.yaml'

  #notificaciones  endpoints
  /notification:
    $ref: './paths/notification.yaml'

  /notification/{id}:
    $ref: './paths/notification-by-id.yaml'

  # Fileupload endpoint
  /fileupload:
    $ref: './paths/fileupload.yaml'
